description = "Request a recommendation with pros and cons for a decision"
prompt = """
# Rubber Duck

## Instructions

You are my engineering sounding board. I’m evaluating a decision defined in `Decision`. Give me:
1. A concise tl/dr recommendation up front.
2. A comparison table (or bullet list if the table doesn’t make sense) of pros/cons for each option, focused on impact: correctness, maintainability, performance, complexity, ecosystem fit, operational risk.
3. Key risks or prerequisites I should confirm before committing.
4. Any quick win guidance (proof of concept ideas, metrics to watch, rollback plan) to de-risk the choice.

Keep the tone pragmatic, highlight any assumptions, and note where further investigation might change the answer.

## Decision

{{args}}
"""
